<?php /* Smarty version 2.6.26, created on 2014-04-07 06:50:28
         compiled from onload_js.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'wm_remove', 'onload_js.tpl', 1, false),array('modifier', 'escape', 'onload_js.tpl', 1, false),array('function', 'load_defer', 'onload_js.tpl', 1, false),)), $this); ?>
<?php func_load_lang($this, "onload_js.tpl","txt_are_you_sure"); ?> <?php ob_start(); ?> <?php if ($_GET['is_install_preview']): ?> <?php echo ' /*  Fix problem with refreshing of the skin preview   */ /*  during skin installation */ var _ts = new Date(); $(\'link\').each(function(){ $(this).attr(\'href\', this.href + \'?\' + _ts.valueOf()); }); '; ?>
 <?php endif; ?> <?php if ($this->_tpl_vars['config']['SEO']['clean_urls_enabled'] == 'Y'): ?> <?php echo ' /*  Fix a.href if base url is defined for page */ function anchor_fix() { var links = document.getElementsByTagName(\'A\'); var m; var _rg = new RegExp("(^|" + self.location.host + xcart_web_dir + "/)#([\\\\w\\\\d_]+)$"); for (var i = 0; i < links.length; i++) {   if (links[i].href && (m = links[i].href.match(_rg))) {     links[i].href = \'javascript:void(self.location.hash = "\' + m[2] + \'");\';   } } } if (window.addEventListener) window.addEventListener("load", anchor_fix, false); else if (window.attachEvent) window.attachEvent("onload", anchor_fix); '; ?>
 <?php endif; ?> <?php echo ' function initDropOutButton() {   if ($(this).hasClass(\'activated-widget\'))     return;   $(this).addClass(\'activated-widget\');   var dropOutBoxObj = $(this).parent().find(\'.dropout-box\');   /* Process the onclick event on a dropout button  */   $(this).click(     function(e) {       e.stopPropagation();       $(\'.dropout-box\').removeClass(\'current\');       dropOutBoxObj         .toggle()         .addClass(\'current\');       $(\'.dropout-box\').not(\'.current\').hide();       if (dropOutBoxObj.offset().top + dropOutBoxObj.height() - $(\'#center-main\').offset().top - $(\'#center-main\').height() > 0) {         dropOutBoxObj.css(\'bottom\', \'-2px\');       }     }   );   /* Click on a dropout layer keeps the dropout content opened */   $(this).parent().click(     function(e) {       e.stopPropagation();     }   );   /* shift the dropout layer from the right hand side  */   /* if it\'s out of the main area */   var borderDistance = ($("#center-main").offset().left + $("#center-main").outerWidth()) - ($(this).offset().left + dropOutBoxObj.outerWidth());   if (!isNaN(borderDistance) && borderDistance < 0) {     dropOutBoxObj.css(\'left\', borderDistance+\'px\');   } } $(document).ready( function() {   $(\'body\').click(     function() {       $(\'.dropout-box\')         .filter(function() { return $(this).css(\'display\') != \'none\'; } )         .hide();     }   );   $(\'div.dropout-container div.drop-out-button\').each(initDropOutButton); } ); '; ?>
 <?php if ($this->_tpl_vars['config']['UA']['browser'] == 'MSIE'): ?> <?php echo ' /* Fix with positioning (z-indexes) */ var i = 100; $(document).ready(function(){ $(".products div.item").each(function() {   $(this).css({\'background-color\' : $(this).css(\'background-color\'), \'z-index\' : i--}); }); change_width_iefix(); }); '; ?>
 <?php endif; ?> <?php echo ' /* Position:absolute elements will not move when window is resized  */ /* if a sibling contains float elements and a clear:both element */ /* bugzilla.mozilla.org/show_bug.cgi?id=442542 */ /* FireFox 3.0+ */ if (navigator.userAgent.toLowerCase().search(/firefox\\/(3\\.\\d+)/i) != -1 && typeof(window.$) != \'undefined\') { $.event.add( window, \'resize\', function() {   var h = document.getElementById(\'header\');   if (!h || $(h).css(\'position\') != \'absolute\')     return;   document.getElementById(\'header\').style.position = \'static\';   setTimeout(     function() {       document.getElementById(\'header\').style.position = \'absolute\';     },   20); }); } '; ?>
 <?php echo ' $(document).ready( function() { $(\'form\').not(\'.skip-auto-validation\').each(function() {   applyCheckOnSubmit(this); }); $(\'a.toggle-link\').live(   \'click\',   function(e) {     $(\'#\' + $(this).attr(\'id\').replace(\'link\', \'box\')).toggle();   } ); }); '; ?>
 <?php echo ' if (products_data == undefined) { var products_data = []; } '; ?>
 var txt_are_you_sure = '<?php echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['lng']['txt_are_you_sure'])) ? $this->_run_mod_handler('wm_remove', true, $_tmp) : smarty_modifier_wm_remove($_tmp)))) ? $this->_run_mod_handler('escape', true, $_tmp, 'javascript') : smarty_modifier_escape($_tmp, 'javascript')); ?>
'; <?php $this->_smarty_vars['capture']['onload_js'] = ob_get_contents(); ob_end_clean(); ?> <?php echo smarty_function_load_defer(array('file' => 'onload_js','direct_info' => $this->_smarty_vars['capture']['onload_js'],'type' => 'js','queue' => '1'), $this);?>
 <?php if ($this->_tpl_vars['active_modules']['EU_Cookie_Law'] != ""): ?> <?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "modules/EU_Cookie_Law/init.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?> <?php endif; ?> <?php if ($this->_tpl_vars['active_modules']['Product_Options'] != ""): ?>   <?php echo smarty_function_load_defer(array('file' => "modules/Product_Options/func.js",'type' => 'js'), $this);?>
 <?php endif; ?> <?php echo smarty_function_load_defer(array('file' => "js/check_quantity.js",'type' => 'js'), $this);?>
 <?php if ($this->_tpl_vars['products'] || $this->_tpl_vars['free_products'] || $this->_tpl_vars['cat_products']): ?> <?php if ($this->_tpl_vars['active_modules']['Feature_Comparison'] && ! $this->_tpl_vars['printable'] && $this->_tpl_vars['products_has_fclasses']): ?> <?php echo smarty_function_load_defer(array('file' => "modules/Feature_Comparison/products_check.js",'type' => 'js'), $this);?>
 <?php endif; ?> <?php endif; ?> 