<?php /* Smarty version 2.6.26, created on 2014-04-07 06:50:28
         compiled from customer/service_css_modules.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'load_defer', 'customer/service_css_modules.tpl', 1, false),)), $this); ?>
 <?php if ($this->_tpl_vars['is_altskin']): ?>  <?php $this->assign('module_css_filename', 'altskin'); ?> <?php else: ?>  <?php $this->assign('module_css_filename', $this->_config[0]['vars']['CSSFilePrefix']); ?> <?php endif; ?> <?php if ($this->_tpl_vars['ie_ver'] != ''): ?> <style type="text/css"> <!-- <?php endif; ?><?php $_from = $this->_tpl_vars['css_files']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['mname'] => $this->_tpl_vars['files']):
?><?php $_from = $this->_tpl_vars['files']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['f']):
?><?php if (! $this->_tpl_vars['f']['admin']): ?><?php if (( ! $this->_tpl_vars['is_altskin'] && ! $this->_tpl_vars['f']['altskin'] ) || ( $this->_tpl_vars['is_altskin'] && $this->_tpl_vars['f']['altskin'] )): ?><?php if (( $this->_tpl_vars['f']['browser'] == $this->_tpl_vars['config']['UA']['browser'] && $this->_tpl_vars['f']['version'] == $this->_tpl_vars['config']['UA']['version'] ) || ( $this->_tpl_vars['f']['browser'] == $this->_tpl_vars['config']['UA']['browser'] && ! $this->_tpl_vars['f']['version'] ) || ( ! $this->_tpl_vars['f']['browser'] && ! $this->_tpl_vars['f']['version'] ) || ( ! $this->_tpl_vars['f']['browser'] )): ?><?php if ($this->_tpl_vars['f']['suffix']): ?><?php echo smarty_function_load_defer(array('file' => "modules/".($this->_tpl_vars['mname'])."/".($this->_tpl_vars['f']['subpath']).($this->_tpl_vars['module_css_filename']).".".($this->_tpl_vars['f']['suffix']).".css",'type' => 'css','css_inc_mode' => $this->_tpl_vars['ie_ver']), $this);?>
<?php else: ?><?php echo smarty_function_load_defer(array('file' => "modules/".($this->_tpl_vars['mname'])."/".($this->_tpl_vars['f']['subpath']).($this->_tpl_vars['module_css_filename']).".css",'type' => 'css','css_inc_mode' => $this->_tpl_vars['ie_ver']), $this);?>
<?php endif; ?><?php endif; ?><?php endif; ?><?php endif; ?><?php endforeach; endif; unset($_from); ?><?php endforeach; endif; unset($_from); ?> <?php if ($this->_tpl_vars['ie_ver'] != ''): ?> --> </style> <?php endif; ?> 